### ISSUE TITLE
Data fetching takes too much time. Around 10 seconds to load data.

### ISSUE THREAD

**Issue by orangewp** [dreamsoftin/flutter_wordpress#10]
How to tackle it?

**Comment by SurajShettigar** [comment]
1. You can reduce the number of posts, comments etc. fetched at a time using `perPage` parameter.
2. When fetching posts through `wordPress.fetchPosts` function, set `fetchAuthor`, `fetchFeaturedMedia` and `fetchComments` to false. It will fetch all those things for each post, which will take time. So you can fetch them seperately after fetching posts, as and when required.

**Comment by rslonik** [comment]
I suggest using `?_embed` in the posts API call as it includes author and featured image data. It takes longer in the WordPress backend, but nowadays any WordPress has caching for that.
