### ISSUE TITLE
The getter 'sourceUrl' was called on null.

### ISSUE THREAD

**Issue by MahdiPishguy** [dreamsoftin/flutter_wordpress#14]
> The getter 'sourceUrl' was called on null.
> Receiver: null
> Tried calling: sourceUrl
> When the exception was thrown, this was the stack:
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
> #1      PostsBuilderState._buildFeaturedMedia (package:flutter_wordpress_example/display_posts.dart:201:69)
> #2      PostsBuilderState._buildPostCard (package:flutter_wordpress_example/display_posts.dart:167:11)
> #3      PostsBuilderState.build.<anonymous closure>.<anonymous closure> (package:flutter_wordpress_example/display_posts.dart:121:28)

**Comment by SurajShettigar** [comment]
As shown in the error log, the error occurs when fetching featured media for the posts. If there are no featured media for the post, its source url will be null. The example was just to show how it can be fetched. We haven't null checked the `imgSource` in line `201` of `display_posts.dart`. You need to check if `imgSource` is `null` before building the widget. 

We'll improve the example project in our next commit.
