### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by MahdiPishguy** [dreamsoftin/flutter_wordpress#15]
Assertion failed
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:

> #0      new MultiChildRenderObjectWidget.<anonymous closure> (package:flutter/src/widgets/framework.dart:1691:11)
> #1      new MultiChildRenderObjectWidget (package:flutter/src/widgets/framework.dart:1696:8)
> #2      new Flex (package:flutter/src/widgets/basic.dart:3707:8)
> #3      new Column (package:flutter/src/widgets/basic.dart:4234:8)
> #4      PostsBuilderState._buildPostCard (package:flutter_wordpress_example/display_posts.dart:156:14)
> #5      PostsBuilderState.build.<anonymous closure>.<anonymous closure> (package:flutter_wordpress_example/display_posts.dart:121:28)

**Comment by SurajShettigar** [comment]
Use the example project just for reference on how some functions of library can be implemented. We are working on improving the example project.
