### ISSUE TITLE
is there any api for us to delete or update  a post?

### ISSUE THREAD

**Issue by luckydogM** [dreamsoftin/flutter_wordpress#20]
is there any api for us to delete or update  a post ? 
it is same to that i can not find these api in flutter_wordpress source code

**Comment by ymakarim** [comment]
I forked the project and **add them**. then I made a pull request yesterday. Unfortunately, it is not added to the original one **yet**. I hope they accept my pull request soon :)

**Comment by yringler** [comment]
The PR https://github.com/dreamsoftin/flutter_wordpress/pull/32 was merged, this can be closed
