### ISSUE TITLE
Custom Post types

### ISSUE THREAD

**Issue by Mayanktaker** [dreamsoftin/flutter_wordpress#25]
How can I use this library to work with custom post types ? 
I created approx 20 custom post types for my app. Is there any way to use Custom Post Types?

**Comment by unluckyxiii** [comment]
Thanks for the great plugin. Any plan to include custom post types?

**Comment by Mayanktaker** [comment]
Any update on custom post types ?

**Comment by Cobolt77** [comment]
#34

**Comment by Mayanktaker** [comment]
Can anyone update the example page with how to call custom post type example ? Like I have /books custom post type. How can I call it on app to fetch all the books ?

**Comment by Cobolt77** [comment]
I got you ! I'll make an example for you tomorrow!

**Comment by Cobolt77** [comment]
Here's a quick example : 
`  
import 'package:flutter_wordpress/flutter_wordpress.dart' as wp;

wp.WordPress wordPress = wp.WordPress(
    baseUrl: 'https://yourdomain.com/',
  );

wordPress.fetchPosts(
      postParams: wp.ParamsPostList(
        context: wp.WordPressContext.view,
        pageNum: 1,
        perPage: 20,
        order: wp.Order.desc,
        orderBy: wp.PostOrderBy.date,
      ),
      fetchAuthor: true,
      fetchFeaturedMedia: true,
      postType: "books"
    );
`

**Comment by Mayanktaker** [comment]
This is the best thing, best comment and best reply I read on 2020. Thanks for the quick help.  👍

**Comment by Cobolt77** [comment]
My pleasure !
