### ISSUE TITLE
Issue regarding using your example app you provide in flutter_wordpress/example/lib

### ISSUE THREAD

**Issue by shahryar-cmyk** [dreamsoftin/flutter_wordpress#29]
**First it giving me this error:**
Android resource linking failed Output: C:\Users\Hp\Desktop\Development\flutter_wordpress\example\build\app\intermediates\incremental\mergeDebugResources\merged.
To Solve this error i change the build.gradle file in flutter_wordpress\example\app.
**compileSdkVersion 27**  to **compileSdkVersion 28** which solve the error.
After this the app is installed and running.
As soon as I pass the username and password in the Form it comes with this error
**SocketException (SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 42706)**.
I don't know how to solve this kindly tell me what i am doing wrong.
**My wordpress site is hosted at localhost with xammp server**

**Comment by SachinGanesh** [comment]
The address is **localhost** only when you are accessing the site from desktop where the site is hosted. If you are accessing the site from mobile (assuming your phone is connected to the same local network) then you should put the IP address of the desktop. not localhost.

**Comment by shahryar-cmyk** [comment]
Thnks
