### ISSUE TITLE
please help with error: A package may not list itself as a dependency

### ISSUE THREAD

**Issue by rays-github** [dreamsoftin/flutter_wordpress#39]
did i not follow step 1 correctly?

Getting Started
1. Import library
First:
Find your pubspec.yaml in the root of your project and add flutter_wordpress: ^0.2.0 under dependencies:
===================================

pubspcc.yaml

name: flutter_wordpress
description: This library uses WordPress REST-API-V2 to provide a way for your application to
  interact with your WordPress website.
version: 0.2.1
authors:
- Sachin Ganesh <sachin@dreamsoftin.com>
- Suraj Shettigar <suraj@dreamsoftin.com>
- Harm-Jan Roskam <harmjanroskam@gmail.com>
- Yahya Makarim <ymakarim@gmail.com>
homepage: https://github.com/dreamsoftin/flutter_wordpress

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  meta: ^1.1.8
  flutter_wordpress: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages

===================================
[flutter_wordpress-master] flutter pub get
Running "flutter pub get" in flutter_wordpress-master...        
Error on line 20, column 3 of pubspec.yaml: A package may not list itself as a dependency.

**Comment by SachinGanesh** [comment]
You are editing the pubspec.yaml file of the plugin itself. Please work on the example folder or create a new project
