### ISSUE TITLE
Type int is not a subtype of type 'String'

### ISSUE THREAD

**Issue by MGD1** [dreamsoftin/flutter_wordpress#40]
i am getting this error when trying to fetch post

![Capture](https://user-images.githubusercontent.com/23202122/84833574-363c6f00-aff5-11ea-934c-5f3cf25bcd30.PNG)

**Comment by GarvMaggu** [comment]
> i am getting this error when trying to fetch post
> 
> ![Capture](https://user-images.githubusercontent.com/23202122/84833574-363c6f00-aff5-11ea-934c-5f3cf25bcd30.PNG)

@MGD1 @SachinGanesh @SurajShettigar This error is caused when the featuredMedia image has a greater height than its width, i.e, it is in portrait. If there are any post which has its featuredMedia as a portrait image, then no post will be fetched and an exception will be thrown, as a workaround, for now, you can do one of these things:

1. Simply turn fetchFeaturedMedia to false
2. Change all featured images on your website to landscape mode.
3. Remove the orientation property completely from ImageMeta in media.dart file.
