### ISSUE TITLE
Add fetchallCategories and fetchallPosts

### ISSUE THREAD

**Issue by yringler** [dreamsoftin/flutter_wordpress#49]
This is something that I need to do. I can't imagine this ever being a good idea in a flutter app, but in a server side app I want to get the entire site and turn it into json optimized for my requirements.

I have to do this one way or another - is it something which you'd be interesting in having in this plugin?

**Comment by SachinGanesh** [comment]
Okay. Others might find it useful too. Please raise a PR

**Comment by yringler** [comment]
Opened a PR (#50 ).
Thoughts?
