### ISSUE TITLE
_TypeError (type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by MeshkaniMohammad** [dreamsoftin/flutter_wordpress#5]
![image](https://user-images.githubusercontent.com/20459019/56475203-93449f80-649a-11e9-98a1-50ac2be67780.png)
I have this error.Help me please

**Comment by SurajShettigar** [comment]
First, handle the Future response returned by wordPress.authenticateUser() function. For example:

```dart
response.then((user) {
  // code
}).catchError((err) {
  print('Failed to fetch user: $err');
});
```

Second, create an admin key if you are using Application passwords as the authenticator in your Wordpress site (refer: https://wordpress.org/plugins/application-passwords/). And put the admin name and key when instantiating WordPress class. For example: 
```dart
wordPress = wp.WordPress(
baseUrl: 'http://localhost',
  authenticator: wp.WordPressAuthenticator.ApplicationPasswords,
  adminName: 'name', 
  adminKey: 'key',
);
```
and then try to authenticate user.

**Comment by MeshkaniMohammad** [comment]
Hi.
I'm confused about"adminkey" and "adminName".
What are these and how to get them?

**Comment by SurajShettigar** [comment]
For authenticating users and for using admin level APIs (create user, posts etc.) you will need to implement some kind of authentication method in your WordPress site. There are some plugins available such as [Application Passwords](https://wordpress.org/plugins/application-passwords/), [JSON Web Tokens (JWT)](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/), etc. You can install any of these two plugins in your WordPress site and the steps to do so are given in the links mentioned above.

In case you use Application Passwords plugin for your site, you generate a key for a user [(refer "CREATING A NEW APPLICATION PASSWORD")](https://wordpress.org/plugins/application-passwords/) and use that key in 
``` dart
wp.WordPress(
baseUrl: 'http://localhost',
  authenticator: wp.WordPressAuthenticator.ApplicationPasswords,
  adminName: 'name', 
  adminKey: 'key',
);
```
Our implementation is not perfect for this plugin, and we will improve it in the future. So I would recommend you use JWT plugin in your site. Then you would not need to use adminName and adminKey parameters, you can call the APIs normally.
