### ISSUE TITLE
JWT problem 

### ISSUE THREAD

**Issue by samatzhusup** [dreamsoftin/flutter_wordpress#63]
i recive in login page: 
I/flutter ( 4103): WordPress Error! code: null, message: {"code":"jwt_auth_invalid_token","message":"Wrong number of segments","data":{"status":403}}, status: null

but in postman work fine:
![2021-02-24_19-21-21](https://user-images.githubusercontent.com/50781959/109006741-9089e580-76d5-11eb-9014-b33e532bc878.png)

**Comment by slayerlp** [comment]
hey did you solve the problem? i get the same issue
