### ISSUE TITLE
can't connect the site using JWT

### ISSUE THREAD

**Issue by ericliu24** [dreamsoftin/flutter_wordpress#7]
` wp.WordPress wordPress = new wp.WordPress(
      // baseUrl: 'http://192.168.6.165',

       baseUrl: 'http://eric-ielts.com',

      authenticator: wp.WordPressAuthenticator.JWT,
    );

    final response =
        wordPress.authenticateUser(username: _username, password: _password);`

The code is above. And my wordpress site has installed the JWT pluggin.

Always say invalid user and password when login, with the log as below:

`I/flutter (15673): WordPress Error! code: null, message: <html>
I/flutter (15673): <head><title>301 Moved Permanently</title></head>
I/flutter (15673): <body bgcolor="white">
I/flutter (15673): <center><h1>301 Moved Permanently</h1></center>
I/flutter (15673): <hr><center>nginx/1.10.2</center>
I/flutter (15673): </body>
I/flutter (15673): </html>
I/flutter (15673): , status: null
`

**Comment by SurajShettigar** [comment]
In the log message, the http error code is 301, so the problem is server sided.
